package org.frc1410.chargedup2023.util;

public interface IDs {
    int DRIVETRAIN_LEFT_FRONT_MOTOR_ID = 1;
    int DRIVETRAIN_RIGHT_FRONT_MOTOR_ID = 2;
    int DRIVETRAIN_LEFT_BACK_MOTOR_ID = 3;
    int DRIVETRAIN_RIGHT_BACK_MOTOR_ID = 4;

    int INTAKE_MOTOR_ID = 5;

    int LBORK_OUTER_ROLLER_ID = 6;
    int LBORK_INNER_ROLLER_ID = 7;

    int INTAKE_FLIPPER_FOWARD_ID = 0;
    int INTAKE_FLIPPER_BACKWARD_ID = 1;
}
