package org.frc1410.chargedup2023.util;

public interface IDs {
	
	// Drivetrain ID's
	int DRIVETRAIN_LEFT_FRONT_MOTOR_ID = 1;
	int DRIVETRAIN_RIGHT_FRONT_MOTOR_ID = 2;
	int DRIVETRAIN_LEFT_BACK_MOTOR_ID = 3;
	int DRIVETRAIN_RIGHT_BACK_MOTOR_ID = 4;

	// Elevator ID's
	int ELEVATOR_LEFT_MOTOR_ID = 11;
	int ELEVATOR_RIGHT_MOTOR_ID = 12;

	int ELEVATOR_LIMIT_SWITCH_PORT = 1;

	int ELEVATOR_ENCODER_ID = 13;

	// LBork rollers
	int LBORK_OUTER_ROLLER_ID = 21;
	int LBORK_INNER_ROLLER_ID = 22;

	// LBork piston ID's
	int LBORK_PISTON_FORWARD_ID = 15;
	int LBORK_PISTON_BACKWARDS_ID = 8;

	// Intake ID's
	int INTAKE_MOTOR_ID = 31;

	// Intake pistons ID's
	int INTAKE_FLIPPER_FORWARD_ID = 1; // 9
	int INTAKE_FLIPPER_BACKWARD_ID = 4;

	int BLINKIN_PORT = 0;
}
