package org.frc1410.chargedup2023.util;

public interface IDs {
	
	// Drivetrain ID's
	int DRIVETRAIN_LEFT_FRONT_MOTOR_ID = 1;
	int DRIVETRAIN_RIGHT_FRONT_MOTOR_ID = 2;
	int DRIVETRAIN_LEFT_BACK_MOTOR_ID = 3;
	int DRIVETRAIN_RIGHT_BACK_MOTOR_ID = 4;

	// Elevator ID's
	int ELEVATOR_MOTOR_ONE_ID = 11;
	int ELEVATOR_MOTOR_TWO_ID = 12;

	int ELEVATOR_BRAKE_FORWARD_ID = 4;
	int ELEVATOR_BRAKE_BACKWARD_ID = 5;

	// LBork rollers
	int LBORK_OUTER_ROLLER_ID = 21;
	int LBORK_INNER_ROLLER_ID = 22;

	// Intake ID's
	int INTAKE_MOTOR_ID = 31;

	// Intake pistons ID's
	int INTAKE_FLIPPER_FORWARD_ID = 0;
	int INTAKE_FLIPPER_BACKWARD_ID = 1;

	// LBork piston ID's
	int LBORK_PISTON_FORWARD_ID = 2;
	int LBORK_PISTON_BACKWARDS_ID = 3;

	int BLINKIN_PORT = 0;
}
